launch_cmd = "cd /cluster/home/pfeene01/CCGaussian; nvidia-smi; pipenv run python ccgaussian/train_gcd.py"

[sbatch]
-p = "gpu"
-t = "0-3:0:0"
--gres = "gpu:a100:1"
-c = 10
-o = "slurm_out/%A_%a.out"
