launch_cmd = "cd /cluster/home/pfeene01/CCGaussian; nvidia-smi; pipenv run python ccgaussian/train_gcd.py"

[sbatch]
-p = "ccgpu"
-t = "0-15:0:0"
--gres = "gpu:a100:1"
-c = 8
-o = "slurm_out/%A_%a.out"
