--lr_e = [1e-6]
--lr_c = [1e-3]
--init_var = [50.0]
--end_var = [5.0]
--w_nll = [0.025]
--w_unlab = [0.5]
--var_warmup = [50]
--num_epochs = [50]
--pseudo_thresh = [0.0]
--gmm_freq = [1, 3, 5, 10]
--batch_size = [256]
