--lr_e = [1e-6]
--lr_c = [1e-3]
--init_var = [50.0]
--end_var = [5.0]
--w_nll = [0.025]
--w_unlab = [0.5, 0.65]
--var_warmup = [50]
--num_epochs = [50]
--pseudo_thresh = [0.8, 0.9, 0.95]
--batch_size = [256]
