--lr_e = [1e-6]
--lr_c = [1e-3]
--init_var = [50.0]
--end_var = [5.0]
--w_nll = [0.0, 0.025]
--w_unlab = [0.5, 1.0]
--var_warmup = [50]
--num_epochs = [50]
--pseudo_thresh = [0.0]
--batch_size = [256]
--dataset_name = ["aircraft", "herbarium_19"]  # "scars"
